echo "Cloudflare Workers Python Auth API Setup"
echo "========================================"
echo ""
echo "Setup Checklist:"
echo "1. Login to Cloudflare: npx wrangler auth login"
echo "2. Create KV namespace: npx wrangler kv:namespace create USERS_KV"
echo "3. Update wrangler.toml with your KV namespace ID"
echo "4. Set secrets:"
echo "   - npx wrangler secret put TURNSTILE_SECRET_KEY"
echo "   - npx wrangler secret put JWT_SECRET_KEY"
echo "5. Test locally: npx wrangler dev"
echo "6. Deploy: npx wrangler deploy"
echo ""
echo "Checking authentication status..."
npx wrangler whoami
echo ""
echo "Ready to start development!"
