name = "secure-auth-api"
main = "src/main.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

[env.production]
name = "secure-auth-api-prod"

[env.staging]
name = "secure-auth-api-staging"

[[kv_namespaces]]
binding = "USERS_KV"
id = "c8976d0499124c8bae3e857aacef5988"
preview_id = "f9d31120a43b469a8ff4fd25b1fd2d61"

[vars]
ENVIRONMENT = "production"

# Secrets are set using wrangler secret commands:
# npx wrangler secret put TURNSTILE_SECRET_KEY
# npx wrangler secret put JWT_SECRET_KEY
